### ISSUE TITLE
Feature request : Add reencode executable

### ISSUE THREAD

**Issue by kpym** [gen2brain/jpegli#1]
It would be nice if you could add `cmd/jpegli` to this module : an executable that can re-encode jpeg files using jpegli.

**Comment by gen2brain** [comment]
There is already a `cjpegli` tool (similar to `cjpeg` from turbo, or `cjxl` from libjx, or `cwebp`, etc. l) in libjxl repo, that will work faster.

**Comment by kpym** [comment]
That makes sense! 

For those looking for the `cjpegli` binary, it can be found in the [`libjxl` releases](https://github.com/libjxl/libjxl/releases). 
_(For Windows you should look for the `static` version)_.
