### ISSUE TITLE
Decode issue with SOI marker

### ISSUE THREAD

**Issue by xjasonlyu** [gen2brain/jpegli#6]
I randomly found this issue when decoding some images using this jpegli pkg on CentOS7.9/amd64 system.

```
lib/jpegli/decode_marker.cc:504: Did not find SOI marker.
```

I have no clues what it means and how to reproduce it, so I reported an issue here.

**Comment by gen2brain** [comment]
There is not much I can do without the image that failed to decode.

**Comment by gen2brain** [comment]
I will close this. Please reopen if you can provide the broken image, you can also send it to me via email.
