### ISSUE TITLE
并发处理导致panic, parallel request will panic

### ISSUE THREAD

**Issue by Shinku-Chen** [gen2brain/jpegli#7]
make(chan bool, 2) or higher . still panic
it is ok when make(chan bool, 1)

```
func TestSync(t *testing.T) {
	wd := sync.WaitGroup{}
	cChan := make(chan bool, 2)
	for i := 0; i < 100; i++ {
		wd.Add(1)
		go func() {
			cChan <- true
			defer func() { <-cChan; wd.Done() }()
			img, _ := jpeg.Decode(bytes.NewReader(testJpg))
			_ = jpegli.Encode(io.Discard, img, nil)
		}()

	}
	wd.Wait()
}
```

**Comment by gen2brain** [comment]
It is fixed in https://github.com/gen2brain/jpegli/commit/5eebe9bc2effff647f85e4abc18d3253665590e7. Now it will instantiate the module on every invocation, it will use more resources but can be safely called concurrently.
